language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.8"
cache: pip
install:
  - pip install tox-travis
  - pip install -r requirements.txt
  - pip install tox coveralls mkdocs mkdocs-material
script:
  - tox -r
after_success:
  - coveralls
  - mkdocs build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: 'site'
  keep-history: true
  verbose: true
  on:
    branch: master
